### ISSUE TITLE
invert

### ISSUE THREAD

**Issue by ouhouhsami** [JasonSanford/geojson-google-maps#1]
hello, 

I found a 'bug' in your code, it seems, you invert 0 and 1
for example, here, your code :
var ll = new google.maps.LatLng(geojsonGeometry.coordinates[i][j][1], geojsonGeometry.coordinates[i][j][0]);
but it seems to be better using this (working for me): 
var ll = new google.maps.LatLng(geojsonGeometry.coordinates[i][j][0], geojsonGeometry.coordinates[i][j][1]);

**Comment by JasonSanford** [comment]
According to the GeoJSON spec (http://geojson.org/geojson-spec.html#positions), the order of coordinates for GeoJSON are [X, Y[, Z]], or in this case [longitude, latitude]. The google.maps.LatLng class expects these values in latitude, longitude order, which would look like:
    var myLatLng = new google.maps.LatLng(myGeoJSONObject.coordinates[1], myGeoJSONObject.coordinates[0]);
