### ISSUE TITLE
Polygon with hole not showing hole - only boundary

### ISSUE THREAD

**Issue by Narrator** [JasonSanford/geojson-google-maps#10]
So, the Geojson for the polygon with hole, I'm using looks like this:

{"type": "Polygon", "coordinates": [ 

[ [ 75.889979740301499, 14.124073402361812 ], [ 79.596655025929664, 14.10023626226131 ], [ 79.554940030753784, 11.871463662864317 ], [ 75.895939025326626, 11.919137943065323 ], [ 75.889979740301499, 14.124073402361812 ] ], 

[ [ 77.4240645, 13.0688045 ], [ 77.4356598, 13.0623401 ], [ 77.4349211, 13.0589817 ], [ 77.436768, 13.0515452 ], [ 77.441693, 13.0429089 ], [ 77.4468644, 13.0257554 ], [ 77.4423087, 13.0195174 ], [ 77.4402154, 13.0087206 ], [ 77.4383686, 13.0087206 ], [ 77.4383686, 13.0112399 ], [ 77.4308579, 13.0114798 ], [ 77.4297497, 13.0066811 ], [ 77.4378761, 13.0059614 ], [ 77.4405849, 13.0000828 ], [ 77.4471106, 12.995164 ], [ 77.446495, 12.984726 ], [ 77.4409543, 12.9812466 ], [ 77.4263022, 12.9829263 ], [ 77.4215002, 12.9712881 ], [ 77.4250709, 12.9667286 ], [ 77.4196532, 12.9670884 ], [ 77.4159595, 12.9586893 ], [ 77.4166982, 12.9481298 ], [ 77.4221158, 12.9470499 ], [ 77.4226084, 12.9405699 ], [ 77.4155901, 12.94081 ], [ 77.4123888, 12.9346899 ], [ 77.4215002, 12.9332498 ], [ 77.4189145, 12.9277296 ], [ 77.4216232, 12.9225693 ], [ 77.4080794, 12.9230493 ], [ 77.4068481, 12.9156087 ], [ 77.4095569, 12.9069676 ], [ 77.395389, 12.9089109 ], [ 77.3934272, 12.909248 ], [ 77.3947816, 12.8919652 ], [ 77.3928116, 12.885964 ], [ 77.3935504, 12.8695199 ], [ 77.4021693, 12.8650786 ], [ 77.4035236, 12.8730008 ], [ 77.4093106, 12.8751614 ], [ 77.4162057, 12.8749213 ], [ 77.4153439, 12.8714403 ], [ 77.4216232, 12.8716805 ], [ 77.4279028, 12.8746813 ], [ 77.4307347, 12.8750414 ], [ 77.4302422, 12.8697599 ], [ 77.4189145, 12.8687997 ], [ 77.423224, 12.860037 ], [ 77.4303654, 12.8564358 ], [ 77.4275334, 12.8500736 ], [ 77.4386149, 12.8492333 ], [ 77.4365217, 12.8465923 ], [ 77.4559758, 12.8392693 ], [ 77.4554833, 12.8327867 ], [ 77.4579458, 12.8276245 ], [ 77.4604084, 12.8275044 ], [ 77.4580689, 12.8203011 ], [ 77.4680422, 12.8096157 ], [ 77.4804781, 12.8078147 ], [ 77.4840488, 12.8154986 ], [ 77.4929139, 12.816099 ], [ 77.4951302, 12.822342 ], [ 77.5019022, 12.822222 ], [ 77.5100286, 12.8267841 ], [ 77.5182781, 12.8235426 ], [ 77.5200019, 12.8127373 ], [ 77.5243112, 12.8114166 ], [ 77.5299752, 12.8127373 ], [ 77.5318221, 12.8139379 ], [ 77.5305908, 12.8163391 ], [ 77.5369934, 12.8193406 ], [ 77.5409335, 12.8164592 ], [ 77.5403178, 12.8145382 ], [ 77.5415491, 12.7972489 ], [ 77.5441348, 12.7949676 ], [ 77.5446273, 12.7982095 ], [ 77.5505374, 12.800971 ], [ 77.558048, 12.7996503 ], [ 77.5557087, 12.7889641 ], [ 77.5621441, 12.7879337 ], [ 77.5639582, 12.7876432 ], [ 77.5629732, 12.7850017 ], [ 77.5562012, 12.7819998 ], [ 77.559895, 12.7671099 ], [ 77.5660514, 12.7591843 ], [ 77.5713458, 12.7608655 ], [ 77.5734389, 12.7656689 ], [ 77.5722077, 12.779238 ], [ 77.581196, 12.787163 ], [ 77.5932625, 12.7811592 ], [ 77.5933856, 12.7773168 ], [ 77.6006287, 12.7795859 ], [ 77.6017368, 12.782828 ], [ 77.6097401, 12.7889517 ], [ 77.6149114, 12.7896722 ], [ 77.6168814, 12.7950754 ], [ 77.614542, 12.8004784 ], [ 77.623284, 12.8038402 ], [ 77.6204521, 12.8112842 ], [ 77.628086, 12.8081626 ], [ 77.6335036, 12.8092431 ], [ 77.6347349, 12.8061215 ], [ 77.6386749, 12.8055212 ], [ 77.6375668, 12.7971165 ], [ 77.6397831, 12.7945951 ], [ 77.6472938, 12.7919535 ], [ 77.6477863, 12.7986774 ], [ 77.6490175, 12.799638 ], [ 77.6488945, 12.8042005 ], [ 77.6624384, 12.8044406 ], [ 77.6598528, 12.8141657 ], [ 77.6633003, 12.8114043 ], [ 77.6647779, 12.8171672 ], [ 77.6779525, 12.8145259 ], [ 77.6818925, 12.8231701 ], [ 77.6858326, 12.8246106 ], [ 77.6870639, 12.8361357 ], [ 77.6893694, 12.8417906 ], [ 77.692974, 12.8397373 ], [ 77.6986378, 12.838897 ], [ 77.7073798, 12.8308536 ], [ 77.7177224, 12.8316939 ], [ 77.7215394, 12.8303733 ], [ 77.7236326, 12.8358957 ], [ 77.7264645, 12.8367361 ], [ 77.7225244, 12.8404576 ], [ 77.7258489, 12.8453795 ], [ 77.7224013, 12.8453795 ], [ 77.7195694, 12.8506615 ], [ 77.7205544, 12.852102 ], [ 77.7300352, 12.8515018 ], [ 77.732744, 12.8569036 ], [ 77.7450567, 12.8524621 ], [ 77.7519518, 12.852342 ], [ 77.7534292, 12.8468199 ], [ 77.7686971, 12.8453795 ], [ 77.7718984, 12.8471802 ], [ 77.7718984, 12.8516218 ], [ 77.7683277, 12.8540226 ], [ 77.7686971, 12.8591844 ], [ 77.7542912, 12.8605048 ], [ 77.7541681, 12.8648261 ], [ 77.7487505, 12.867827 ], [ 77.7563844, 12.8693875 ], [ 77.7568769, 12.874789 ], [ 77.7641414, 12.8847514 ], [ 77.7654958, 12.8929131 ], [ 77.7635258, 12.8990341 ], [ 77.7683277, 12.8996343 ], [ 77.7701746, 12.9103158 ], [ 77.7726372, 12.9106758 ], [ 77.7744841, 12.9214769 ], [ 77.7807635, 12.9219569 ], [ 77.784088, 12.9293973 ], [ 77.7779316, 12.9327574 ], [ 77.7767004, 12.9377976 ], [ 77.7760847, 12.9404375 ], [ 77.7833492, 12.9433176 ], [ 77.7839649, 12.9451176 ], [ 77.7728834, 12.9509974 ], [ 77.7752228, 12.9547172 ], [ 77.7750997, 12.9592769 ], [ 77.778301, 12.9643165 ], [ 77.7917219, 12.9645565 ], [ 77.7909831, 12.9679161 ], [ 77.7871662, 12.9683961 ], [ 77.7858118, 12.9715157 ], [ 77.780271, 12.9715157 ], [ 77.7771929, 12.9741553 ], [ 77.7774391, 12.976555 ], [ 77.7817486, 12.9800345 ], [ 77.7887668, 12.9818342 ], [ 77.7964007, 12.9946717 ], [ 77.7936919, 13.0049893 ], [ 77.7891362, 13.0063089 ], [ 77.7906137, 13.0144666 ], [ 77.7988632, 13.0121873 ], [ 77.8018182, 13.0285021 ], [ 77.7913525, 13.0255031 ], [ 77.7835955, 13.0267027 ], [ 77.7813739, 13.0474782 ], [ 77.7746072, 13.0476945 ], [ 77.7741147, 13.0504532 ], [ 77.7702977, 13.0504532 ], [ 77.769559, 13.055491 ], [ 77.7605707, 13.0562107 ], [ 77.7593103, 13.0597652 ], [ 77.7494892, 13.065806 ], [ 77.7363147, 13.0653263 ], [ 77.734714, 13.0728823 ], [ 77.7264645, 13.073482 ], [ 77.7238788, 13.0767203 ], [ 77.7025779, 13.0758807 ], [ 77.6999922, 13.0895529 ], [ 77.695929, 13.0896728 ], [ 77.7013465, 13.1114987 ], [ 77.7047942, 13.1141369 ], [ 77.6907577, 13.1291259 ], [ 77.6922352, 13.1362004 ], [ 77.682385, 13.1364401 ], [ 77.6790606, 13.1282865 ], [ 77.6557896, 13.1262481 ], [ 77.6566515, 13.1333227 ], [ 77.6454469, 13.1375194 ], [ 77.6417531, 13.1340421 ], [ 77.635843, 13.1364401 ], [ 77.6369511, 13.1459126 ], [ 77.6197134, 13.1576625 ], [ 77.6199596, 13.1679732 ], [ 77.6122026, 13.1677335 ], [ 77.6124489, 13.1743273 ], [ 77.600013, 13.172529 ], [ 77.5847453, 13.1742074 ], [ 77.5751414, 13.1772046 ], [ 77.5718169, 13.1825993 ], [ 77.5608586, 13.1827192 ], [ 77.5623361, 13.1755262 ], [ 77.5512547, 13.1664147 ], [ 77.5460834, 13.1685727 ], [ 77.5448521, 13.1728887 ], [ 77.5315544, 13.1720494 ], [ 77.5342632, 13.1635373 ], [ 77.5322931, 13.1592211 ], [ 77.5272449, 13.1543054 ], [ 77.5204729, 13.1576625 ], [ 77.5122234, 13.1569431 ], [ 77.5114847, 13.1465121 ], [ 77.4981868, 13.14891 ], [ 77.4979407, 13.1370398 ], [ 77.4879674, 13.1407568 ], [ 77.4847661, 13.132963 ], [ 77.4771322, 13.1328431 ], [ 77.4771322, 13.1298454 ], [ 77.4793485, 13.1281667 ], [ 77.4800872, 13.1225308 ], [ 77.4819342, 13.1191733 ], [ 77.4779941, 13.1147365 ], [ 77.4736847, 13.1138971 ], [ 77.4743003, 13.1291259 ], [ 77.471099, 13.1304449 ], [ 77.4708527, 13.1335625 ], [ 77.4632189, 13.1357208 ], [ 77.4628495, 13.1260083 ], [ 77.4564469, 13.1286463 ], [ 77.4546, 13.1178543 ], [ 77.45854, 13.1146166 ], [ 77.4594019, 13.0980676 ], [ 77.457555, 13.0948297 ], [ 77.4452423, 13.092671 ], [ 77.4447498, 13.0818774 ], [ 77.4261576, 13.0828368 ], [ 77.4240645, 13.0688045 ]]]}

Why is this not loading as a hole in a polygon?

**Comment by gmccrackin** [comment]
I think I fixed it. Clone my current fork and if it works I will send him a pull request.

**Comment by Narrator** [comment]
It works! Thank you :)

**Comment by gmccrackin** [comment]
I submitted a pull request.
