### ISSUE TITLE
package.json for npm

### ISSUE THREAD

**Issue by franz-josef-kaiser** [JasonSanford/geojson-google-maps#16]
Would really be nice to have that one added as it's most popular and most convenient option:

```
"dependencies": {
    "geoJSON-to-Google-Maps": "1.0.x"
},
```

Guess the `package.json` would look something like this: 

```
{
    "name": "geoJSON-to-Google-Maps",
    "version": "1.0.0",
    "description": "Just a simple utility to convert GeoJSON objects to Google Maps vector objects (Marker, Polyline, Polygon)",
    "author": "Jason Sanford <jasonsanford@gmail.com>",
    "dependencies": {
        "express": ">= 1.0.0",
        "optimist": ">= 1.0.0"
    },
    "engine": "node 0.6.x"
}
```

which would need to be aligned by a [registration on the NPM package repo](https://npmjs.org/).

Thanks in advance!

**Comment by JasonSanford** [comment]
This seems like a food idea. I'm not very familiar with NPM, but why would this package have express/optimist dependencies?

**Comment by franz-josef-kaiser** [comment]
> This seems like a food idea

seems like you got hungry as well :)

Ad dependencies) Whoops! Per accident by copy/pasting from original example file at node/npm HQ.

**Comment by JasonSanford** [comment]
Ugh, train typing :/

**Comment by franz-josef-kaiser** [comment]
I won't register it to the repository (better the account is in your hands), but do you need a pull request for the JSON file?

**Comment by JasonSanford** [comment]
Sure, but maybe hold off for a few hours maybe? I'm thinking about changing the name of this repo. Crazy-cased-Repo-name seemed like a good idea a few years back, but not so much now. Thinking of the bad things that could happen if I change the name.

**Comment by JasonSanford** [comment]
Ok, I changed the name. I'd be happy to merge a pull request and register at NPM at some point. I'm not sure, but I thought I needed to have the code structured in a specific way for it to be a true NPM module? correct? (module.exports or something)

**Comment by franz-josef-kaiser** [comment]
> Sure, but maybe hold off for a few hours maybe?

Sure. Updated to new name. Currently using `bower.js` to fetch the repo like this:

<pre>{
  "name": "geojsontests",
  "version": "0.0.1",
  "main": "assets/styles/main.css",
  "ignore": [
    ".git",
    "assets/scripts/vendor",
    "assets/styles/vendor",
    "node_modules"
  ],
  "dependencies": {
    "geojson-google-maps": "https://github.com/JasonSanford/geojson-google-maps.git"
  }
}
</pre>

Never heard or read about any npm package file/folder organisation. At least nothing that I can [read on the official page](https://npmjs.org/doc/developers.html).

**Comment by justincy** [comment]
What would be the point of registering it with npm? It's only useful in the browser. Do people use npm packages in the browser?

**Comment by franz-josef-kaiser** [comment]
NPM is as well a repository. So you simply open your preferred CLI, type `npm whatever` and NPM searches the repository for matches. Btw, @justincy why "only useful in the browser"? Are you mixing something up? NPM = Node.js Package Manager...

At the current point I don't use NPM for this repo, but simply bower to install it. Closed therefore.

**Comment by justincy** [comment]
@franz-josef-kaiser Yeah I wasn't clear. I meant to say "this google maps library is only useful in the browser".
