### ISSUE TITLE
v2 for handling Google Maps -> GeoJSON

### ISSUE THREAD

**Issue by justincy** [JasonSanford/geojson-google-maps#20]
I wrote a version 2.0 of this utility to handle conversion from Google Maps overlays to GeoJSON ([my fork](https://github.com/openplacedatabase/geojson-google-maps)).

List of changes:
- mounted functions in the `google.maps.geojson` namespace (`google.maps.geojson.fromGeoJSON()` instead of `new GeoJSON()`)
- created `google.maps.geojson.toGeoJSON()`
- removed duplicate points in GeoJSON polygons for closing rings when converting to GMaps overlays
- setup a test suite using QUnit which tests GeoJSON -> GMaps, GMaps -> GeoJSON, and GeoJSON -> GMaps -> GeoJSON

`toGeoJSON()` is designed to handle the output of `fromGeoJSON()`, though it only handles a subset because I'm not sure how/if it could handle features and collections. The old interactive test page has a perfect example for this:

```
 {
  "type": "GeometryCollection",
  "geometries": [
    {
      "type": "Point",
      "coordinates": [-80.66256, 35.04271]
    },{
      "type": "MultiPolygon",
      "coordinates": [
        [
          [
            [-80.661917125299155, 35.042245264120233],
            [-80.662257428469147, 35.042566288770765],
            [-80.662116500253873, 35.042670715828088],
            [-80.661715367137106, 35.042389935257198],
            [-80.661917125299155, 35.042245264120233]
          ]
        ],[
          [
            [-80.661547137566686, 35.042510563404129],
            [-80.661677171806787, 35.042417322902836],
            [-80.662084018102888, 35.042702102858307],
            [-80.662039854197829, 35.042756211162953],
            [-80.662002555672572, 35.042820528162387],
            [-80.661457640151127, 35.042647387136952],
            [-80.661547137566686, 35.042510563404129]
          ]
        ]
      ]
    },{
      "type": "LineString",
      "coordinates": [
        [-80.661983228058659, 35.042968081213758],
        [-80.662076494242413, 35.042749414542243],
        [-80.662196794397431, 35.042626481357232],
        [-80.664238981504525, 35.041175532632963]
      ]
    }
  ]
}
```

When this is converted to GMaps overlays, you have this:

```
[
  Marker,
  [
    Polygon,
    Polygon
  ],
  Polyline
]
```

The problem here is that I can't know if the two Polygons are part of a MultiPolygon or a nested GeometryCollection. It's easy to conceive of more complicated examples. If we can't find a method for generating GeoJSON GeometryCollections such that it **always** matches the input to `fromGeoJSON()` then I'd rather not deal with it and just let the user manage the complexity if they're ever unlucky enough to need that functionality.

**Comment by justincy** [comment]
And I just changed the names of the functions to just `from` and `to` after realizing the `GeoJSON` part was redundant (and ugly).

**Comment by JasonSanford** [comment]
Sorry for not following up on this sooner. Did you want to submit this as a Pull Request? All of the changes look good to me, except that binding these methods to the `google` global scares me a bit, not sure why though.
