### ISSUE TITLE
Problem with adding Multipolygon in GeometryCollection object

### ISSUE THREAD

**Issue by choweric** [JasonSanford/geojson-google-maps#5]
I was trying to put in a bunch of Polygons and Multipolygons in a GeometryCollection object, but it seems only the Polygons show up on the map, but NOT the Multipolygons.

**Comment by gmccrackin** [comment]
If you show me the geoJSON Ill try and help you.

**Comment by choweric** [comment]
Take a look at here:

http://gundam.hk/geojsn/

I modified the example file, and appended the MultiPolygon objects (the two trapezoid objects near "1002" on the map) into the GeometryCollection object. I appended it between the Point and the LineString objects in the GeometryCollection.

Then, pressing "GeoJSON GeometryCollection" button, I was expecting it gives me a marker, two trapezoids and a line. Instead, it only gives me the marker. It seems the rendering of the MultiPolygon is already causing problem. In fact, all other buttons stops working thereafter. 

Eric

**Comment by JasonSanford** [comment]
Sorry, for some reason I wasn't getting messages for this issue. I'll try to take a closer look very soon.

**Comment by gmccrackin** [comment]
It looks like there was a problem rendering the geometries that were arrays. So I added a for loop to deal with it.
Here is the link to the commit or you can just clone my experimental branch.
https://github.com/gmccrackin/GeoJSON-to-Google-Maps/commit/50f9b8563c99fae451252c0daae604d54eccdba6

**Comment by choweric** [comment]
Hi there. Thanks for the quick fix! 
The rendering is fine now on the demo (http://gundam.hk/geojsn/ ; GeoJSON GeometryCollection button).
However, after the rendering of geometry collection, I clicked on other buttons and nothing works. 
I suspect it's not doing the "clearMap" properly afterward?

**Comment by gmccrackin** [comment]
lol sorry. I did it quickly because I was on the way out. Ill try and look at it here in a sec.

**Comment by gmccrackin** [comment]
I fixed the clear map function. Here is a link to the commit if you want to see the change or just pull my master.
https://github.com/gmccrackin/GeoJSON-to-Google-Maps/commit/4f2a90fecb66fdfcb1fdf161e5ae28cc34a2f48b

I tried to test everything out this time. If you do see a problem tell me though.

**Comment by JasonSanford** [comment]
Sorry guys. I've been quite busy so just watching from the sidelines here. If @gmccrackin has a good fix, please send a pull request and I'll merge with master.

**Comment by choweric** [comment]
Thanks a lot for the effort! It's working great now. :)
