### ISSUE TITLE
Please License Under Something Permissive

### ISSUE THREAD

**Issue by bobbysmith007** [JasonSanford/geojson-google-maps#8]
It would be super fantastic if this has a license file / text block somewhere indicating that it is cool to use it.  It would be doubly fantastic if the license was something permissive like BSD / MIT.

Thanks for the software, I appreciate your efforts on our behalf.

[A Sample BSD License](http://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29)

**Comment by JasonSanford** [comment]
Yep, I created this before realizing that a license file and more specifically a proper license is a really good thing to have. I've done this on some of my [other](https://github.com/JasonSanford/google-vector-layers) [projects](https://github.com/JasonSanford/leaflet-vector-layers) with a BSD license and will do the same here. If I don't do this in the next day or two ping me again  ... been occupied with other things lately.

**Comment by JasonSanford** [comment]
I added a LICENSE file. BSD. I hope this helps.

**Comment by bobbysmith007** [comment]
awesome, thanks so much!
