### ISSUE TITLE
'Donut' geometries missing the holes

### ISSUE THREAD

**Issue by k-dahl** [JasonSanford/geojson-google-maps#9]
I've found that the geometries that come through GeoJSON.js seem to be missing any holes - any ideas on how to fix this? When I load the json data up in QGIS it displays fine there, so I know it's not the data. I did see a javascript implementation of a JSON > Google Maps feature elsewhere that supposedly takes into consideration polygons with internal rings like this, but unfortunately my JS knowledge is not sufficient to debug that particular implementation or factor it into your code. It's here if you'd like to take a look:

http://friism.com/drawing-geojson-based-polygons-on-google-maps/comment-page-1#comment-1651

**Comment by gmccrackin** [comment]
Some of the other issues already take a look at this. Have you pulled recently? The index actually has an example of a polygon with an interior ring. If you give me some example GeoJSON that doesn't work I can try to fix it.

**Comment by k-dahl** [comment]
Here is one of the specific polygons I am having the issue with, and I am using the latest revision of GeoJSON.js...

``` javascript
var polydata = 
{
        "type":"FeatureCollection",
        "features":[
            { "type":"Feature", "id":8,
                "properties":{
                    "AREA":46147406.683990,
                    "PERIMETER":41165.214250,
                    "PD_ID":831478,
                    "PD_NUM":9,
                    "PD_NBR_SFX":"0",
                    "PD_TYPE":"N",
                    "ADV_POLL":"600",
                    "ED_ID":1351,
                    "FED_NUM":35012,
                    "A_UPDT_DTE":"2006\/10\/30",
                    "G_UPDT_DTE":"2003\/08\/27",
                    "EMRP_NAME":"9",
                    "OBJECTID":1448411,
                    "SHAPE_AREA":46147406.233300,
                    "SHAPE_LEN":41165.214292
                },
                "geometry":{
                    "type":"Polygon",
                    "coordinates":[
                        [
                            [ -76.165286, 45.479514 ],
                            [ -76.140095, 45.457437 ],
                            [ -76.162348, 45.444872 ],
                            [ -76.168656, 45.441087 ],
                            [ -76.201963, 45.420225 ],
                            [ -76.213668, 45.429276 ],
                            [ -76.214261, 45.429917 ],
                            [ -76.227477, 45.440383 ],
                            [ -76.263056, 45.467983 ],
                            [ -76.245084, 45.468609 ],
                            [ -76.240206, 45.471202 ],
                            [ -76.238518, 45.475254 ],
                            [ -76.233483, 45.507829 ],
                            [ -76.227816, 45.511836 ],
                            [ -76.212117, 45.516230 ],
                            [ -76.191776, 45.501540 ],
                            [ -76.174016, 45.486911 ],
                            [ -76.165286, 45.479514 ]
                        ],

                        [
                            [ -76.227618, 45.489247 ],
                            [ -76.232113, 45.486983 ],
                            [ -76.232151, 45.486379 ],
                            [ -76.231812, 45.485106 ],
                            [ -76.230698, 45.483236 ],
                            [ -76.225664, 45.477365 ],
                            [ -76.223568, 45.475174 ],
                            [ -76.202829, 45.458815 ],
                            [ -76.200229, 45.458822 ],
                            [ -76.199069, 45.459164 ],
                            [ -76.188361, 45.465784 ],
                            [ -76.204505, 45.479018 ],
                            [ -76.215555, 45.488534 ],
                            [ -76.220249, 45.492175 ],
                            [ -76.221154, 45.493315 ],
                            [ -76.226310, 45.490189 ],
                            [ -76.226543, 45.489754 ],
                            [ -76.227618, 45.489247 ]
                        ]
            ] } }

        ]
    };
```

I tried the example Polygon/Hole and it most certainly does work, and I also enclosed it in a feature collection and had no issues either. I'm making the assumption that the data I am using is correctly formatted as it does appear correctly when I open the GeoJSON file directly in QGIS, but it could just be that QGIS is handling an issue in the data that I am unaware of.

**Comment by gmccrackin** [comment]
Maybe I am missing the point but when I use your GeoJSON example it seems to work fine. This is what I get and it looks like its correct. http://i1160.photobucket.com/albums/q483/gmccrackin/ScreenShot2012-03-09at21048PM.png

**Comment by k-dahl** [comment]
It seems it's me that's missing the point, as I grabbed the latest GeoJSON.js and you're correct it works fine... I'm not sure how I ended up with an older version as I only downloaded it a few days back and the last edit from the history seems to be 17 days ago. Regardless, thanks for your time - and sorry if I wasted it!

**Comment by gmccrackin** [comment]
no problem dude. Im just glade it wasn't faulty.

**Comment by JasonSanford** [comment]
Thanks for picking up my slack @gmccrackin. Glad you're all fixed up @blitzd.
